services:
  web:
    build: .
    # Em produção (EasyPanel), não sobrescreva o código com "."
    # Mas precisamos de persistência para o banco de dados
    volumes:
      - finance_data:/app/data
    ports:
      - "8000:8000"
    restart: always

volumes:
  finance_data:
