# Generated by Django 6.0 on 2026-01-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_instance_id', models.CharField(blank=True, help_text='ID da instância da Evolution API (ex: bc8e8300-...)', max_length=255, null=True, verbose_name='ID da Instância WhatsApp')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
