# Generated by Django 6.0 on 2026-01-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='anthropic_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Anthropic API Key'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='deepseek_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DeepSeek API Key'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='default_ai_provider',
            field=models.CharField(choices=[('ollama', 'Ollama (Qwen)'), ('deepseek', 'DeepSeek'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic (Claude)')], default='ollama', max_length=20, verbose_name='Provedor de IA Padrão'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gemini API Key'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ollama_model',
            field=models.CharField(default='qwen2.5-coder:3b-instruct-q4_K_M', max_length=100, verbose_name='Modelo Ollama'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='ollama_url',
            field=models.URLField(default='https://eden-ollama.w2zld5.easypanel.host/v1', verbose_name='URL do Ollama'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OpenAI API Key'),
        ),
    ]
