# Generated by Django 6.0 on 2026-01-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_appsettings_anthropic_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='whatsapp_allowed_numbers',
            field=models.TextField(blank=True, default='244956834375@s.whatsapp.net', help_text='Lista de JIDs ou números autorizados, separados por vírgula. Ex: 244956834375@s.whatsapp.net, 123456789', null=True, verbose_name='Números Permitidos (WhatsApp)'),
        ),
    ]
