# Generated by Django 6.0 on 2026-01-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_appsettings_whatsapp_allowed_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='whatsapp_allowed_numbers',
            field=models.TextField(blank=True, help_text='Lista de números (separados por vírgula) autorizados a interagir com o bot, mesmo que fromMe seja true. Ex: 244956834375, 551199999999', null=True, verbose_name='Números WhatsApp Autorizados'),
        ),
    ]
